# Challenge_1
References:
1. Microsoft. (n.d.). Calculate the smallest or largest number in a range. Microsoft Support. Retrieved March 22, 2023, from https://support.microsoft.com/en-us/office/calculate-the-smallest-or-largest-number-in-a-range-45fe249f-96c3-443b-8e9f-87f16c48462c#:~:text=1%20Select%20a%20cell%20below%20or%20to%20the,the%20largest%29%2C%20and%20then%20press%20ENTER.%20See%20More Used to verify the formula needed for calculating the Minimum and Maximum of a data range. Used in Sheet named "Statistical Analysis"
2. Microsoft. (n.d.). Video: COUNTIFS and SUMIFS. Microsoft Support. Retrieved March 22, 2023, from https://support.microsoft.com/en-us/office/countifs-function-dda3dc6e-f74e-4aee-88bc-aa8c2a866842 Used to verify the formula needed to countif with multiple criteria. Formula used in Sheet named "Goal Analysis"
3.  Cheusheva , S. (2023, March 14). Excel filter function with formula examples. ablebits.com. Retrieved March 22, 2023, from https://www.ablebits.com/office-addins-blog/excel-filter-function/ Link provided by Payson Cushman in Slack. Used to learn the FILTER function. Filter function was used in Sheet "Statistical Analysis"
4.  Microsoft. (n.d.). Filter function. Microsoft Support. Retrieved March 22, 2023, from https://support.microsoft.com/en-us/office/filter-function-f4f7cb66-82eb-4767-8f7c-4877ad80c759 Used to learn the FILTER function. Filter function was used in Sheet "Statistical Analysis"
5.  Microsoft Q&amp;A- new columns do not show as pivot table fields. Microsoft. (n.d.). Retrieved March 22, 2023, from https://answers.microsoft.com/en-us/msoffice/forum/all/new-data-columns-do-not-show-as-pivot-table-fields/5232406e-1e08-4760-80f2-72fa65485463 Used to figure out how to refresh the pivot table to add newly added columns to the pivot table fields. Used in sheets "PARENTCAT VS OUTCOME" and "SUBCAT VS OUTCOME"
6.  Microsoft- Split text into different columns with functions . Microsoft Support. (n.d.). Retrieved March 23, 2023, from https://support.microsoft.com/en-us/office/split-text-into-different-columns-with-functions-49ec57f9-3d5a-44b2-82da-50dded6e4a68 Used to figure out how to split information from one column into two separate ones. Used in sheet "Crowdfunding"
7.  Frolov, A. (n.d.). Excel textbefore function - extract text before character (delimiter). ablebits.com. Retrieved March 22, 2023, from https://www.ablebits.com/office-addins-blog/excel-textbefore-function-extract-text-before-character/ Used to figure out how to split information from one column into two separate ones. Used in sheet "Crowdfunding"
8.  Sun. (2023, March 5). How to convert between date and unix timestamp in Excel? ExtendOffice. Retrieved March 22, 2023, from https://www.extendoffice.com/documents/excel/2473-excel-timestamp-to-date.html#a3 Provided by Module 1 instructions. Used to learn the formula to convert Timestamps to Dates.
